quay/urls.py
from django.conf.urls import patterns, include, url
from rest_framework import viewsets, routers
from cms.models import *
from cms.serializers import *
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()


reservation_info = { 'queryset': Reservation.objects.all() }


class ReservationViewSet(viewsets.ModelViewSet):
    model = Reservation
    queryset = Reservation.objects.all()
    serializer_class = ReservationSerializer

router = routers.DefaultRouter()
router.register(r'cms', ReservationViewSet)


from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'quay.views.home', name='home'),
    # url(r'^quay/', include('quay.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$',               'cms.views.home',            name='home'),
    url(r'^menu',            'cms.views.menu',            name='menu'),
    url(r'^about',           'cms.views.about',           name='about'),
    url(r'^functions',       'cms.views.functions',       name='functions'),
    url(r'^contact',         'cms.views.contact',         name='contact'),
    url(r'^food-philosophy', 'cms.views.foodPhilosophy',  name='foodPhilosophy'),
    url(r'^our-producers',   'cms.views.ourProducers',    name='ourProducers'),
    url(r'^reviews-media',   'cms.views.reviewsMedia',    name='reviewsMedia'),
    url(r'^awards',          'cms.views.awards',          name='awards'),
    url(r'^news-events',     'cms.views.newsEvents',      name='newsEvents'),
    url(r'^our-team',        'cms.views.ourTeam',         name='ourTeam'),
    url(r'^employment',      'cms.views.employment',      name='employment'),
    url(r'^reservation/',    'cms.views.reservation',     name='reservation'),
    url(r'^subscribe/',      'cms.views.subscribe',       name='subscribe'),
    url(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': 'media/'}),
    url(r'^api/', include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

)

cms/models.py
# AboutPage
# Award
# AwardPage
# BookImage
# Book
# Background
# ContactPage
# Contact
# Course
# OpeningHours
# Dish
# EmploymentPage
# FoodPhilosophyPage
# FunctionsPage
# HomePage
# Media
# Menu
# MenuCategory
# MenuPage
# NewsArticle
# NewsPage
# NewsEventsPage
# OurProducersPage
# OurTeamPage
# Positions
# Producer
# Reservation
# ReservationForm
# ReviewsMediaPage
# Team


from pytz import timezone
from django import forms
from pprint import pprint
from datetime import datetime
from django.db import models
from django.utils import formats
import string
from django.forms import ModelForm
from django.utils.html import strip_tags
from django.template.defaultfilters import slugify
from sortedm2m.fields import SortedManyToManyField

####################################################################
# Partials
####################################################################

class NewsArticle(models.Model):
  title            = models.CharField(max_length=255)
  description      = models.CharField(max_length=1000)
  date             = models.DateField(auto_now=False, blank=True, null=True)
  image            = models.FileField(upload_to='news/', blank=True)
  published        = models.BooleanField(default=False)
  reservation_link = models.BooleanField(default=False)
  published_at     = models.DateTimeField(auto_now=True)
  created_at       = models.DateTimeField(auto_now=True)
  def __unicode__(self):
    return self.title + '  -  created: ' + formats.date_format(self.created_at, "SHORT_DATE_FORMAT")

class Award(models.Model):
  title            = models.CharField(max_length=255)
  description      = models.CharField(max_length=1000)
  image            = models.FileField(upload_to='award_images/', blank=True)
  team_image       = models.FileField(upload_to='images/', blank=True)
  created_at       = models.DateTimeField(auto_now=True)

class BookImage(models.Model):
  cssClass         = models.CharField(max_length=255)
  created_at       = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return unicode(self.cssClass)

class Book(models.Model):
  title            = models.CharField(max_length=255, default='')
  sub_title_line_1 = models.CharField(max_length=255, default='')
  sub_title_line_2 = models.CharField(max_length=255, default='')
  author           = models.CharField(max_length=255, default='')
  sub_author       = models.CharField(max_length=255, default='')
  description      = models.CharField(max_length=1500, default='')
  book_image       = models.ForeignKey(BookImage, null=True)
  link             = models.CharField(max_length=255, default='')
  quote            = models.CharField(max_length=500, default='')
  quote_author     = models.CharField(max_length=255, default='')
  position         = models.IntegerField(blank=False, default=0)
  created_at       = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return unicode(self.title)

class Background(models.Model):
  cssClass         = models.CharField(max_length=255)
  created_at       = models.DateTimeField(auto_now=True)

  def __unicode__(self):
      return unicode(self.cssClass)

  def image_thumb(self):
    path = 'bg/bg-'
    end = ''
    if any(self.cssClass[:-3] in s for s in ['uppertower','greenroom','restaurant']):
      path = 'rooms/'
    else:
      end = '-375'
    return '<img src="../../../../../static/images/%s%s%s.jpg" width="100" />' % (path,self.cssClass,end)
  image_thumb.allow_tags = True

class Contact(models.Model):
  address_line_1   = models.CharField(max_length=250)
  address_line_2   = models.CharField(max_length=250)
  address_line_3   = models.CharField(max_length=250)
  tel              = models.CharField(max_length=250)
  fax              = models.CharField(max_length=250)
  email            = models.CharField(max_length=250)

class OpeningHours(models.Model):
  lunch_service    = models.CharField(max_length=250)
  dinner_service   = models.CharField(max_length=250)

class Dish(models.Model):
  name             = models.CharField(max_length=1500)
  description      = models.CharField(max_length=1500)
  def __unicode__(self):
    return unicode(self.name)

class Course(models.Model):
  course_title     = models.CharField(max_length=250)
  course_number    = models.CharField(max_length=250)
  dishes           = SortedManyToManyField(Dish)
  def __unicode__(self):
    return unicode(self.course_title)

class MenuCategory(models.Model):
  category         = models.CharField(max_length=250)
  def __unicode__(self):
    return unicode(self.category)

class Positions(models.Model):
  job_title        = models.CharField(max_length=250)
  job_description  = models.CharField(max_length=5000)
  active           = models.BooleanField(default=False)
  def __unicode__(self):
    return unicode(self.job_title)

class Menu(models.Model):
  category         = models.ForeignKey(MenuCategory)
  courses          = SortedManyToManyField(Course)
  prices           = models.CharField(max_length=250)
  additional_info  = models.CharField(max_length=1000, null=True, blank=True)
  active           = models.BooleanField(default=False)
  created_at       = models.DateTimeField(auto_now=True)
  def __unicode__(self):
    return unicode(self.category.category)
  # def item_list(self):
  #   # return [item.description for item in Menu_item.objects.filter(menu=self).order_by('order')]
  #   return [item.description for item in self.menu_item.order_by('order')]


####################################################################
# Pages
####################################################################

class HomePage(models.Model):
  background       = models.ManyToManyField(Background)
  welcome_copy     = models.CharField(max_length=500)
  menu_copy        = models.CharField(max_length=500)
  menu_copy2       = models.CharField(max_length=500)
  function_copy    = models.CharField(max_length=500)
  about_copy       = models.CharField(max_length=500)
  news_article     = models.ForeignKey(NewsArticle)
  display_promo    = models.BooleanField(default=False)
  active           = models.BooleanField(default=False)
  created_at       = models.DateTimeField(auto_now=True)
  # def __unicode__(self):
  #   return unicode([(field.name, field.value_to_string(self)) for field in self._meta.fields])
  def __unicode__(self):
    return 'Home page   -  created: ' + formats.date_format(self.created_at, "SHORT_DATE_FORMAT")
class MenuPage(models.Model):
  background       = models.ForeignKey(Background)
  intro            = models.CharField(max_length=500)
  additional_info  = models.CharField(max_length=1500)
  philosophy       = models.CharField(max_length=500)
  our_produce      = models.CharField(max_length=500)
  display_promo    = models.BooleanField(default=False)
  wines_list       = models.FileField(upload_to='pdf', blank=True)
  active           = models.BooleanField(default=False)
  created_at       = models.DateTimeField(auto_now=True)
  def __unicode__(self):
    return 'Menu page   -  created: ' + formats.date_format(self.created_at, "SHORT_DATE_FORMAT")

class AboutPage(models.Model):
  headline         = models.CharField(max_length=255)
  intro_copy       = models.CharField(max_length=1000)
  background       = models.ForeignKey(Background)
  news_article     = models.ForeignKey(NewsArticle)
  books            = models.ManyToManyField(Book)
  active           = models.BooleanField(default=False)
  created_at       = models.DateTimeField(auto_now=True)

  def image_thumb(self):
    path = 'bg/bg-'
    end = ''
    if any(self.background.cssClass[:-3] in s for s in ['uppertower','greenroom','restaurant']):
      path = 'rooms/'
    else:
      end = '-375'
    return '<img src="../../../../../static/images/%s%s%s.jpg" width="100" />' % (path,self.background.cssClass,end)
  image_thumb.allow_tags = True

  def __unicode__(self):
    return 'About page   -  created: ' + formats.date_format(self.created_at, "SHORT_DATE_FORMAT")


class NewsPage(models.Model):
  headline         = models.CharField(max_length=255)
  intro_copy       = models.CharField(max_length=1000)
  background       = models.ForeignKey(Background)
  news_articles    = models.ManyToManyField(NewsArticle)
  created_at       = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return unicode(self.headline)

class EmploymentPage(models.Model):
  headline         = models.CharField(max_length=255)
  intro_copy       = models.CharField(max_length=1000)
  background       = models.ForeignKey(Background)
  jobs             = SortedManyToManyField(Positions)
  created_at       = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return unicode(self.headline)

class SpecialContact(models.Model):
  title         = models.CharField(max_length=255)
  image         = models.ImageField(upload_to='peoples/', blank=True)
  name          = models.CharField(max_length=255)
  function      = models.CharField(max_length=255)
  phone         = models.CharField(max_length=255, blank=True, null=True)
  fax           = models.CharField(max_length=255, blank=True, null=True)
  email         = models.EmailField(max_length=255)
  active        = models.BooleanField(default=False)
  created_at    = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return unicode(self.title)

class FunctionsPage(models.Model):
  headline         = models.CharField(max_length=255)
  intro_copy       = models.CharField(max_length=1000)
  background       = models.ForeignKey(Background, related_name='functionspage_background')

  uppertower_image = models.ForeignKey(Background, related_name='functionspage_uppertower_image')
  uppertower_copy1 = models.CharField(max_length=2000)
  uppertower_copy2 = models.CharField(max_length=2000)
  uppertower_carou = SortedManyToManyField(Background, related_name='functionspage_uppertower_carou')
  

  greenroom_image  = models.ForeignKey(Background, related_name='functionspage_greenroom_image')

reservations/views.py
from reservations.models import *
from django.template import RequestContext
from django.http import HttpResponse
from django.shortcuts import *
from pprint import pprint
import json
from quay import  settings
from django.core.mail import EmailMultiAlternatives
from createsend import *

def reservation(request):
     if request.method == 'POST':
            form = ReservationForm(request.POST)

            if form.is_valid():
                e = Reservation()

                e.full_name =  form.cleaned_data['full_name']
                e.email_address =  form.cleaned_data['email_address']
                e.company = form.cleaned_data['company']
                e.personal_phone =  form.cleaned_data['personal_phone']
                e.hotel_phone =  form.cleaned_data['hotel_phone']
                e.postcode =  form.cleaned_data['postcode']
                e.num_people =  form.cleaned_data['num_people']
                e.lunch_dinner = form.cleaned_data['lunch_dinner']
                e.special_requests = form.cleaned_data['special_requests']
                e.optin = form.cleaned_data['optin']

                combinedDateTime =  form.cleaned_data['date'] + form.cleaned_data['time']
                e.reservation_time = datetime.strptime(combinedDateTime,'%d %B, %Y%H:%M')

                e.save()

                link = "http://"+request.META['HTTP_HOST']+ '/admin/reservations/reservation/' + str(e.id)


                html_body = settings.EMAIL_HTML_BODY % {'reservation_link':link,'reservation_time':e.reservation_time,'full_name':e.full_name, 'email_address':e.email_address, 'company':e.company ,'personal_phone':e.personal_phone ,'hotel_phone':e.hotel_phone,'postcode':e.postcode,'num_people':e.num_people,'special_requests':e.special_requests}
                text_body = settings.EMAIL_HTML_BODY % {'reservation_link':link,'reservation_time':e.reservation_time,'full_name':e.full_name, 'email_address':e.email_address, 'company':e.company ,'personal_phone':e.personal_phone ,'hotel_phone':e.hotel_phone,'postcode':e.postcode,'num_people':e.num_people,'special_requests':e.special_requests}

                local_tz = timezone('Australia/Sydney')

                now_sydney= local_tz.localize(e.reservation_time)
                fmt = "%Y-%m-%d"
                subject_stub = e.full_name + " " +  now_sydney.strftime(fmt)
                subject = settings.EMAIL_SUBJECT % {'description': subject_stub}

                email = EmailMultiAlternatives(subject,  text_body, settings.EMAIL_FROM, [settings.EMAIL_TO],[settings.EMAIL_TO_ADMIN],headers={'Reply-To':e.email_address})
                email.attach_alternative(html_body, "text/html")

                mail_error = False

                try:
                    email.send(fail_silently=False)
                    sub = Subscriber({'api_key': '403fe978bf82ea531d01edef9f576523'})
                    sub.add('8a9f7433251762b2432b357997fc9329',e.email_address,e.full_name ,'',True,False)

                    if (e.optin == True):
                      sub.add('acc1ede6a129663ee85063617682554e',e.email_address,e.full_name ,'',True,False)


                except Exception, e:
                    mail_error = True


                response_data = {}
                response_data['title'] = 'THANK YOU<br>FOR YOUR ENQUIRY'
                response_data['para'] = 'Your enquiry has been sent. We will reply to your enquiry shortly. We do receive a high volume of reservations requests daily. Please allow at least 48 hours in which to reply to your request.'

                return HttpResponse(json.dumps(response_data),content_type="application/json")

            else:

                return HttpResponse(json.dumps({"": ""}),content_type="application/json")
     else:
            form = ReservationForm()


     return render_to_response('reservation.html', {'form': form,}, context_instance=RequestContext(request))

templates/old/reservation.html
{% extends "base.html" %}

{% block main %}

<form id="reservation_form" action = "/reservation/" autocomplete="on" method = "POST">
      {% csrf_token %}
  <div class="panel full first">
    <div class="floatlabel-wrapper push">
      <label for="id_full_name">Full name</label>
      <input id="id_full_name" type="text" placeholder="Eg. John Smith" name="full_name">
    </div>
    <div class="floatlabel-wrapper">
      <label for="id_company">Company Name (optional)</label>
      <input id="id_company" type="text" placeholder="Eg. Quay Restaurant" name="company">
    </div>
    <div class="floatlabel-wrapper phone-wrapper">
      <label for="id_personal_phone">Phone No.</label>
      <input id="id_personal_phone" type="tel" placeholder="Eg. 02 9251 5600" name="personal_phone">
    </div>
    <div class="floatlabel-wrapper push postcode-wrapper">
      <label for="id_postcode">Postcode</label>
      <input id="id_postcode" type="number" placeholder="2000" name="postcode">
    </div>
    <div class="floatlabel-wrapper">
      <label for="id_hotel_phone">Contact No. in Sydney or hotel</label>
      <input id="id_hotel_phone" type="tel" placeholder="Eg. 02 9251 5600" name="hotel_phone">
    </div>

  </div>

  <div class="panel full dark">
    <div class="floatlabel-wrapper push">
      <label for="id_date">Date of requested reservation</label>
      <input id="id_date" type="text" placeholder="DD / MM / YYYY" name="date" class="datepicker"><span class="icon-calendar"></span>
    </div>
    <div class="radio">
      <label for="lunch_dinner">Time of day</label>
      <div class="radio-wrapper">
        <input id="lunch" type="radio" name="lunch_dinner" value="lunch">
        <label for="lunch"><span class="icon-tick"></span>Lunch</label>
        <input id="dinner" type="radio" name="lunch_dinner" value="dinner">
        <label for="dinner"><span class="icon-tick"></span>Dinner</label>
      </div>
    </div>
   <div class="floatlabel-wrapper time-select">
      <label for="id_time">Time</label>
      <select id="id_time" type="text" data-placeholder="Select" name="time" class="classic">
        <option value="12:00">12:00 PM</option>
        <option value="12:30">12:30 PM</option>
        <option value="13:00">13:00 PM</option>
        <option value="13:30">13:30 PM</option>
        <option value="14:00">14:00 PM</option>
        <option value="18:00">18:00 PM</option>
        <option value="18:30">18:30 PM</option>
        <option value="19:00">19:00 PM</option>
        <option value="19:30">19:30 PM</option>
        <option value="20:00">20:00 PM</option>
        <option value="20:30">20:30 PM</option>
        <option value="21:00">21:00 PM</option>
        <option value="21:30">21:30 PM</option>
        <option value="22:00">22:00 PM</option>
      </select>
    </div>
    <div class="floatlabel-wrapper people-select push">
      <label for="id_num_people">People (max 9)</label>
      <select id="id_num_people" type="text" data-placeholder="Select" name="num_people" class="classic">
        <option value="one">One</option>
        <option value="two">Two</option>
        <option value="three">Three</option>
        <option value="four">Four</option>
        <option value="five">Five</option>
        <option value="six">Six</option>
        <option value="seven">Seven</option>
        <option value="eight">Eight</option>
        <option value="nine">Nine</option>
      </select>
    </div>
    <div class="floatlabel-wrapper">
      <label for="id_email_address">Email address</label>
      <input id="id_email_address" type="email" placeholder="Eg. john@email.com" name="email_address">
    </div>
  </div>
  <div class="panel full">
      <div class="floatlabel-wrapper comment-wrapper">
        <label for="id_special_requests">Special requests or comments (optional)</label>
        <input id="id_special_requests" type="text" placeholder="Eg. Dietary Requirements" name="special_requests">
      </div>
      <div class="clear">
        <input id="id_optin" type="checkbox" name="optin">
        <label for="id_optin"><span class="icon-tick"></span>Yes I wish to SUBSCRIBE TO the Quay Newsletter</label>
      </div>
  </div>

  <div class="panel full">
    <input type="submit" value="submit" name="button" class="button">
    <div class="throbber"></div>
  </div>

</form>





{% endblock %}